bot:
  token: UNKNOWN
  channel_id: UNKNOWN

db:
  driver: 'postgres'
  address: 'localhost'
  port: 5432

openai:
  key: ''
  prompt: ''

server:
  fetch_interval: '10m'
  notification_interval: '1m'
  filterKeywords: []
